### ISSUE TITLE
Epic: Management of the APIs

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/prototype#63]
Ampersand prototypes have a number of special API-calls that are very helpful for developers. There are API calls for exporting the database population, and for exporting a CSV file that reports on the time consumption of the various rules/conjuncts that have been evaluated, and I expect there to be more.

This issue calls for an extension of the prototype menu that already allows us to reinstall the database, i.e. to add items to that menu that, when selected, invoke such APIs. 

Complete following tasks/user stories:
- Mapping #133 -> making list of APIs
- #134 
- #135

**Comment by LiWeiYeh** [comment]
@Michiel-s is this issue the same as [#133](https://github.com/AmpersandTarski/prototype-frontend/issues/133)? The provided issues for #134 and #135 cannot be found.

**Comment by Michiel-s** [comment]
Those issues are in a different repo. Therefore you need to specify the issue like this: `organization/repo#id`

Note. This issue here (#63) is the Epic. Consisting of 3 user stories:
* 133: AmpersandTarski/prototype-frontend#133
* 134: AmpersandTarski/prototype-frontend#134
* 135: AmpersandTarski/prototype-frontend#135

So, if 133 is fixed, then this epic is completed
